{% set version = "4.0.3" %}

package:
  name: spandx
  version: {{ version }}

source:
  url: https://github.com/dsarov/spandx/archive/v{{ version }}.tar.gz # [linux64,linux32]

build:
  number: 0

requirements:
  build:
      - {{ compiler('cxx') }}
  host:
      - art
      - trimmomatic
      - bwa
      - bedtools
      - seqtk
      - pindel
      - mosdepth
      - samtools=1.9
      - picard
      - gatk4
      - snpEff=4.3.1t
      - nextflow
      - fasttree
  run:
      - art
      - trimmomatic
      - bwa
      - bedtools
      - seqtk
      - pindel
      - mosdepth
      - samtools=1.9
      - picard
      - gatk4
      - snpEff=4.3.1t
      - nextflow
      - fasttree

test:
  commands:
      - nextflow -h

about:
  home: 'https://github.com/dsarov/SPANDx'
  license: MIT
  license_file: LICENSE
  summary: 'SPANDx: a comparative genomics pipeline'
